kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: adservice
  name: adservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: adservice
  template:
    metadata:
      labels:
        k8s-app: adservice
    spec:
      containers:
      - name: adservice
        image: gcr.io/aliz-tiket-sandbox/k8s-adservice:latest 
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
